version: '3.2'
services:
  db:
     image: postgres
     environment:
       #- POSTGRES_PASSWORD=password1
       - POSTGRES_USER=courtbot
       - POSTGRES_DB=courtbot
     ports:
       - "54320:5432"
     #volumes:
     #- ./db-init-scripts:/docker-entrypoint-initdb.d
     #   - ../backup/backup/backups:/backups/
  courtbot-setup:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./app
        target: /app/app
    environment:
      DECLARE_LOCATION: 'Roseville'
      COOKIE_SECRET: 'supply_a_real_value'
      DATABASE_URL: postgres://courtbot:password1@db:5432/courtbot
      HEROKU_POSTGRESQL_NAVY_URL: postgres://courtbot:password1@db:5432/courtbot
    depends_on:
      - db
    command: [ "node", "utils/index.js" ]
    # utils/createQueuedTable.js" ]

  courtbot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./app
        target: /app/app
    ports:
      - "5000:5000"
    environment:
      DECLARE_LOCATION: 'Roseville'
      COOKIE_SECRET: 'supply_a_real_value'
      DATABASE_URL: postgres://courtbot:password1@db:5432/courtbot
      HEROKU_POSTGRESQL_NAVY_URL: postgres://courtbot:password1@db:5432/courtbot
    command: [ "npm", "start" ]
    depends_on:
      - db
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules

